services:

  postgres:
    container_name: postgres-container
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: task_manager_db
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - custom-network
    restart: unless-stopped

  task-manager-backend:
    container_name: task-manager-backend
    image: rupesh1997/task-manager-backend:1.0.0
    ports:
      - 8181:8181
    volumes:
      - task-manager-backend-storage:/app/uploads
    networks:
      - custom-network
    depends_on:
      - postgres

  task-manager-frontend:
    container_name: task-manager-frontend
    image: rupesh1997/task-manager-frontend:1.0.0
    ports:
      - 8080:80
    networks:
      - custom-network
    depends_on:
      - task-manager-backend

networks:
  custom-network:
    driver: bridge

volumes:
  postgres:
    driver: local
  task-manager-backend-storage:
    driver: local

#docker-compose -f docker/docker-compose.yml up -d