application:
  cors:
    origins: http://localhost:4200,http://localhost:8080
  security:
    token:
      expires_in: 86400000
      secret_key: AB23CD76BD23JH87KL98HJ57BG76TE00LL00TTG86AB23CD76BD23JH87KL98HJ57BG76TE00LL00TTG86AB23CD76BD23JH87KL98HJ57BG76TE00LL00TTG86

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/task_manager_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect

server:
  port: 9090

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type: trace