application:
  cors:
    origins: http://localhost:4200,http://localhost:8080,http://20.55.25.220:8080,http://20.55.25.220:8181
  security:
    token:
      expires_in: 86400000
      secret_key: AB23CD76BD23JH87KL98HJ57BG76TE00LL00TTG86AB23CD76BD23JH87KL98HJ57BG76TE00LL00TTG86AB23CD76BD23JH87KL98HJ57BG76TE00LL00TTG86

spring:

  datasource:
    url: jdbc:postgresql://localhost:5432/task_manager_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8181

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type: trace